services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - testDb
    env_file:
      - .env.test
    command: npm run start:dev
    volumes:
      - .:/usr/src/app 
      - /usr/src/app/node_modules
  testDb:
    image: postgres:12
    ports:
      - "5444:5432"
    env_file:
      - .env.test
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
