services:
  api-test:
    build: .
    ports:
      - "3001:3000"
    depends_on:
      - testDb
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_TYPE: ${POSTGRES_TYPE}
      POSTGRES_PORT: ${POSTGRES_PORT}
    command: npm run start:dev
    volumes:
      - .:/usr/src/app 
      - /usr/src/app/node_modules
    networks:
      - incourage-test
      
  testDb:
    image: postgres:12
    ports:
      - "5444:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_TYPE: ${POSTGRES_TYPE}
      POSTGRES_PORT: ${POSTGRES_PORT}
    networks:
      - incourage-test

networks:
  incourage-test:
    driver: bridge
    name: incourage-test
