services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - testDb
    env_file:
      - .env.test
    command: npm run start:dev
    volumes:
      - .:/usr/src/app 
      - /usr/src/app/node_modules
    networks:
      - incourage-test
      
  testDb:
    image: postgres:12
    ports:
      - "5444:5432"
    env_file:
      - .env.test
    networks:
      - incourage-test

networks:
  incourage-test:
    driver: bridge
    name: my-app-network
