services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env.local
    command: npm run start:dev
    volumes:
      - .:/usr/src/app 
      - /usr/src/app/node_modules
    networks:
      - incourage-dev

  db:
    image: postgres:12
    ports:
      - "5432:5432"
    env_file:
      - .env.local
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - incourage-dev

volumes:
  pgdata:

networks:
  incourage-dev:
    driver: bridge
    name: incourage-dev